### ISSUE TITLE
Typo: 'RIFGH JOIN' should be 'RIGHT JOIN'

### ISSUE THREAD

**Issue by rexxiang** [ByteByteGoHq/system-design-101#12]
file path: [images/how-to-learn-sql.jpg](https://github.com/ByteByteGoHq/system-design-101/blob/main/images/how-to-learn-sql.jpg)

`RIFHT JOIN` should be `RIGHT JOIN`

<img width="660" alt="image" src="https://github.com/ByteByteGoHq/system-design-101/assets/3139369/18dac5dc-e415-4f1d-94cf-f2db268aeb4f">

**Comment by UsmanLiaqat404** [comment]
@rexxiang, I have addressed this issue and submitted a pull request for your review.
